### ISSUE TITLE
Add Android Project Gradle instructions

### ISSUE THREAD

**Issue by realdm** [rharter/ktor-moshi#1]
It would be good to add the instructions to download the library on an android project.
Example: 
## Download

Add a gradle dependency to your project:

```groovy
compile 'com.ryanharter.ktor:ktor-moshi:1.0.0'
```

Add a gradle dependency to your android project:

```groovy
implementation 'com.ryanharter.ktor:ktor-moshi:1.0.0'
```

**Comment by rharter** [comment]
Thanks, @realdm, but how would you use this for Android projects?  Are you running a Ktor server in an Android app?

**Comment by realdm** [comment]
Not really, I thought about trying to do that ;)

**Comment by rharter** [comment]
Since Ktor is a backend server framework and using the server portion of it on Android wouldn't be more than experimental, I'm going to close this.  

If you get it running on Android please share :)
